on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore: ['**.md', 'docs/**']
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
    timeout-minutes: 15
